export const GET_INTRADAY_PRICES_REQUESTED = "GET_INTRADAY_PRICES_REQUESTED";
export const GET_INTRADAY_PRICES_SUCCESS = "GET_INTRADAY_PRICES_SUCCESS";
export const GET_INTRADAY_PRICES_FAILED = "GET_INTRADAY_PRICES_FAILED";

export const GET_YESTERDAY_CLOSE_PRICES_REQUESTED = "GET_YESTERDAY_CLOSE_PRICES_REQUESTED";
export const GET_YESTERDAY_CLOSE_PRICES_SUCCESS = "GET_YESTERDAY_CLOSE_PRICES_SUCCESS";
export const GET_YESTERDAY_CLOSE_PRICES_FAILED = "GET_YESTERDAY_CLOSE_PRICES_FAILED";

export const GET_HISTORICAL_DATA_REQUESTED = "GET_HISTORICAL_DATA_REQUESTED";
export const GET_HISTORICAL_DATA_SUCCESS = "GET_HISTORICAL_DATA_SUCCESS";
export const GET_HISTORICAL_DATA_FAILED = "GET_HISTORICAL_DATA_FAILED";