export const GET_INTRADAY_PRICES_REQUESTED = "GET_INTRADAY_PRICES_REQUESTED";
export const GET_INTRADAY_PRICES_SUCCESS = "GET_INTRADAY_PRICES_SUCCESS";
export const GET_INTRADAY_PRICES_FAILED = "GET_INTRADAY_PRICES_FAILED";

export const GET_YESTERDAY_CLOSE_REQUESTED = "GET_YESTERDAY_CLOSE_REQUESTED";
export const GET_YESTERDAY_CLOSE_SUCCESS = "GET_YESTERDAY_CLOSE_SUCCESS";
export const GET_YESTERDAY_CLOSE_FAILED = "GET_YESTERDAY_CLOSE_FAILED";