name: "Stock Market unit tests"

on: push

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Test
        run: npm test
        env:
          REACT_APP_SANDBOX_API_KEY: Tsk_635cd392492e41418ddf866cf145a3cb
          REACT_APP_SANDBOX_BASE_URL: https://sandbox.iexapis.com/
